### ISSUE TITLE
Fonts fix (fontpaths.res)

### ISSUE THREAD

**Issue by tacogamma** [tekunotri/optive-hud#1]
![image](https://github.com/tekunotri/optive-hud/assets/70152439/1e335a5d-399d-4833-ae95-2bdadd3c3111)

Forgot to add Scheme { ... } at the start

**Comment by tekunotri** [comment]
fixed as of e394c2225923f3dba2ae4f56cf271a37539bd753. thanks for reporting!

fix will be on comfig soon
